### ISSUE TITLE
Completed module 2 assignment

### ISSUE THREAD

**Issue by jonathanosas** [ds4owd-001/md-02-assignments-jonathanosas#1]
Apologies I am completing my module 2 assignment late. I am committed to completing all tasks for this course even if I missed the class. I am trying to catch up on all assignments before module 4 on 28th. @larnsce @mianzg

**Comment by larnsce** [comment]
No problem, @jonathanosas. Is there something we can support you with?

**Comment by larnsce** [comment]
@jonathanosas, I will close this issue now. Please reach out to us if we can support you in any way.
